### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by di48l069** [Joshwoo70/UpNet#4]
Is this application so in development had similar concept I would like to build in C# if you interested?

MMO hacking style game strictly console based.

**Comment by Joshwoo70** [comment]
> Is this application so in development had similar concept I would like to build in C# if you interested?
MMO hacking style game strictly console based.

MMO? no this game is not mmo based. the reason is that running a mmo will be costly and time comsuming. also the plan is to get the main code from uplink ported over to upnet,

**Comment by di48l069** [comment]
@Joshwoo70 I see
